director_uuid: <%= %x[bosh status --uuid] %>

vm_type: nano

persistent_disk_type: 10240

azs: [AZ]

network_name: service

vm_password: echo -n 'password' | mkpasswd --method=sha-512 --password-fd=0

